### ISSUE TITLE
issue-1-use-navigation

### ISSUE THREAD

**Issue by christine-tina-park** [christine-tina-park/ajax-project#1]
## ⚙️ Feature

User can use the navigation.

## 📐 Functionality

User can click on the header navigation buttons to navigate between different pages.

## 🖼️ Wireframes

![Screen Shot 2021-09-22 at 10 32 56 AM](https://user-images.githubusercontent.com/88121218/134393162-554bb945-9624-4662-8bce-18069d81da89.png) ![Screen Shot 2021-09-22 at 10 33 21 AM](https://user-images.githubusercontent.com/88121218/134393185-52de4987-f249-4e41-b492-0c4a1fee050a.png)

## ✅ Task List

- [ ] Create the header with current page name and the navigation buttons in the desktop view.
- [ ] Create the header with current page name and the dropdown navigation.
- [ ] 
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
