### ISSUE TITLE
issue-2-generate-wheel-of-life

### ISSUE THREAD

**Issue by christine-tina-park** [christine-tina-park/ajax-project#2]
## ⚙️ Feature

User can generate Wheel of Life.

## 📐 Functionality

User can input a score from 0 through 10 for each category, which will automatically generate Wheel of Life and update it every time user inputs a new value.

## ✅ Task List

- [ ] Create the default Wheel of Life.
- [ ] Create 10 categories with a dropdown selector for score of 0 through 10.
- [ ] Make sure that Wheel of Life gets updated every time user inputs a new value.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
