### ISSUE TITLE
issue-3-create-an-entry-in-vision-board

### ISSUE THREAD

**Issue by christine-tina-park** [christine-tina-park/ajax-project#3]
## ⚙️ Feature

User can create an entry in Vision Board.

## 📐 Functionality

User can create an entry by clicking the Add (+) Button and filling out the form with Photo Url and Life Goal.

## ✅ Task List

- [ ] Create the default page of Vision Board.
- [ ] Create the Add (+) Button.
- [ ] Open the pop-up form when user clicks on the Add Button.
- [ ] Show image when user inputs Photo Url.
- [ ] When user submits the form, store information in local storage.
- [ ] When the user submits the form, show the list of entries in Vision Board without the need to refresh the page.
- [ ] Make sure the most recent entry is listed at the top.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
