### ISSUE TITLE
issue-4-modify-an-entry-in-vision-board

### ISSUE THREAD

**Issue by christine-tina-park** [christine-tina-park/ajax-project#4]
## ⚙️ Feature

User can modify an entry in Vision Board.

## 📐 Functionality

User can click Edit Button next to an entry in Vision Board to modify (either edit or delete) the entry.

## ✅ Task List

- [ ] When the user clicks on Edit Button, show a pop-up form with the options of Cancel, Delete, and Submit.
- [ ] Populate the form values with the corresponding entry's pre-existing values.
- [ ] When the user clicks on Cancel, close the pop-up.
- [ ] When the user clicks on Submit, update data model and DOM element value with new values.
- [ ] When the user clicks on Delete, delete the entry info from data model and DOM element.
- [ ] After Submit or Delete, automatically show the updated list of entries in Vision Board.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
