### ISSUE TITLE
issue-5-view-quote-of-the-day

### ISSUE THREAD

**Issue by christine-tina-park** [christine-tina-park/ajax-project#5]
## ⚙️ Feature

User can view Quote of the Day.

## 📐 Functionality

User can navigate to the Quote of the Day page, which will display a random inspirational quote.

## ✅ Task List

- [ ] Create the default Quote of the Day page with quotation mark images.
- [ ] Every time the user clicks on the page navigation, display a new inspirational quote.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
